### ISSUE TITLE
[Bug] Switching to correct tool after mining with the wrong one causes target block to be instamined

### ISSUE THREAD

**Issue by elhertz** [RamGemes/use-the-tool#1]
How to reproduce:
- Have a 1.21 dedicated server with `Fabric Loader 0.16.2` - `fabric-api 0.102.0+1.21` & `Use the tool-0.0.1+1.20.5-1.21`
- Join with a vanilla client
- Example: mine diamond ore with gold pickaxe (it won't break), afterwards switch your tool with an iron or diamond one (it will insta break)

**Comment by Ramixin** [comment]
Hello @elhertz, Use The Tool! is designed to be used on both the server and client. The use of the mod on only one is not supported and may lead to undefined behavior. After a quick test, this is not an issue when installed on both ends.
